name: test the things

on:
  push:
    branches:
      - main  # Set a branch to deploy
  pull_request:

jobs:
  pylint:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - run: |
            python3 -m venv venv
            source venv/bin/activate
            python3 -m pip install --upgrade --quiet pip
            python3 -m pip install --quiet -r requirements-dev.txt
            python3 -m pylint --rcfile=.pylintrc fail2ban_importer
      - run: |
            source venv/bin/activate
            python3 -m mypy fail2ban_importer
  mypy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - run: |
            python3 -m venv venv
            source venv/bin/activate
            python3 -m pip install --upgrade --quiet pip
            python3 -m pip install --quiet -r requirements-dev.txt
      - run: |
            source venv/bin/activate
            python3 -m mypy fail2ban_importer

